import '@/styles/globals.css'
import { Montserrat } from 'next/font/google'
import Head from 'next/head'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

import NavBar from '@/components/NavBar'
import ImageBackgroundContainer from '@/components/ImageBackgroundContainer'
import Footer from '@/components/Footer'

const montserrat = Montserrat({
    subsets: ['latin'],
    variable: '--font-mont',
})

export default function App({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>AG Portfolio | Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/images/header-logo.png" />
            </Head>
            <main
                className={`${montserrat.variable} font-mont bg-[#28283c] w-full min-h-screen`}
            >
                <NavBar />
                <Component {...pageProps} />

                <Footer />
            </main>
            <ToastContainer
                position="bottom-right" // Position of the toast
                autoClose={5000} // Duration before toast closes
                hideProgressBar={true} // Show progress bar
                closeOnClick // Close on click
                pauseOnHover // Pause on hover
            />
        </>
    )
}
